import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/logging/app_logger.dart';
import 'firebase_options.dart';

/// Application entry point.
///
/// Initializes Firebase, then hosts all Riverpod providers in a single [ProviderScope]
/// (EOS-003-P2 §10 — no service locator, no global singletons).
///
/// NOTE: `firebase_options.dart` is generated by `flutterfire configure --project=hilo-23078`.
/// Run that once (see flutter-app/README.md) before building.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  AppLogger.info('HiLo app starting');
  runApp(const ProviderScope(child: HiLoApp()));
}
