import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/logging/app_logger.dart';
import 'firebase_options.dart';

/// Application entry point.
///
/// Initializes Firebase, then hosts all Riverpod providers in a single [ProviderScope]
/// (EOS-003-P2 §10 — no service locator, no global singletons).
///
/// `firebase_options.dart` is generated by `flutterfire configure --project=hilo-23078`.
///
/// For fully-local development against the Firebase Emulator Suite (no billing/credentials),
/// pass `--dart-define=USE_FIREBASE_EMULATOR=true`; the auth-service backend must also point
/// at the emulator (FIREBASE_AUTH_EMULATOR_HOST / FIRESTORE_EMULATOR_HOST).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  const useEmulator = bool.fromEnvironment('USE_FIREBASE_EMULATOR');
  if (useEmulator) {
    const host = String.fromEnvironment('FIREBASE_EMULATOR_HOST', defaultValue: 'localhost');
    await FirebaseAuth.instance.useAuthEmulator(host, 9099);
    AppLogger.info('Using Firebase Auth emulator at $host:9099');
  }

  AppLogger.info('HiLo app starting');
  runApp(const ProviderScope(child: HiLoApp()));
}
