import type { Venue } from '../domain/venue.js';

/**
 * Seed venues around Hyderabad (launch market) for local development and tests — used by
 * the in-memory catalogue repo and the fake Location Service until the real Google Places
 * adapter is wired (needs Maps Platform billing + key).
 */
export const HILO_SEED_VENUES: Venue[] = [
  {
    id: 'ven_hilo_taj',
    source: 'hilo',
    name: 'Taj Krishna Banquet',
    address: 'Banjara Hills, Hyderabad',
    city: 'Hyderabad',
    category: 'Banquet Hall',
    latitude: 17.4156,
    longitude: 78.4347,
    capacity: 500,
    rating: 4.6,
    reviewCount: 1200,
    pricePerPlate: 1800,
    amenities: ['parking', 'ac', 'catering', 'wheelchair'],
    photos: [],
    verified: true,
    trustScore: 0.92,
    reviewSentiment: 0.88,
    indoor: true,
  },
  {
    id: 'ven_hilo_lawn',
    source: 'hilo',
    name: 'Green Meadows Lawn',
    address: 'Gachibowli, Hyderabad',
    city: 'Hyderabad',
    category: 'Wedding Lawn',
    latitude: 17.44,
    longitude: 78.348,
    capacity: 900,
    rating: 4.2,
    reviewCount: 430,
    pricePerPlate: 1100,
    amenities: ['parking', 'catering'],
    photos: [],
    verified: true,
    trustScore: 0.81,
    reviewSentiment: 0.79,
    indoor: false,
  },
  {
    id: 'ven_hilo_party',
    source: 'hilo',
    name: 'Skyline Rooftop',
    address: 'Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    category: 'Rooftop Venue',
    latitude: 17.431,
    longitude: 78.407,
    capacity: 120,
    rating: 4.4,
    reviewCount: 260,
    pricePerPlate: 1500,
    amenities: ['ac', 'catering', 'alcohol'],
    photos: [],
    verified: true,
    trustScore: 0.86,
    reviewSentiment: 0.83,
    indoor: false,
  },
];

export const GOOGLE_SEED_VENUES: Venue[] = [
  {
    id: 'ven_g_novotel',
    source: 'google',
    googlePlaceId: 'gplace_novotel',
    name: 'Novotel Convention Centre',
    address: 'HITEC City, Hyderabad',
    city: 'Hyderabad',
    category: 'Convention Centre',
    latitude: 17.4435,
    longitude: 78.3772,
    capacity: 800,
    rating: 4.4,
    reviewCount: 900,
    priceLevel: 3,
    amenities: ['parking', 'ac', 'catering'],
    photos: [],
    verified: false,
    indoor: true,
  },
  {
    id: 'ven_g_hall',
    source: 'google',
    googlePlaceId: 'gplace_community',
    name: 'Community Function Hall',
    address: 'Kukatpally, Hyderabad',
    city: 'Hyderabad',
    category: 'Community Hall',
    latitude: 17.4849,
    longitude: 78.4138,
    capacity: 300,
    rating: 3.9,
    reviewCount: 150,
    priceLevel: 1,
    amenities: ['parking'],
    photos: [],
    verified: false,
    indoor: true,
  },
];
